"""The replay path must cover every figure the repo ships.

Training this repo end to end is hours of CPU, so ``experiments/
reproduce_figures.py`` -- committed logs and checkpoints back into figures --
is the reproducibility story a reader actually gets. Its value is exactly its
coverage, and coverage rots silently: a figure added without a replay path
looks fine in the README and cannot be regenerated by anyone.

So compare the declared list against the directory, in both directions, and
check that every artifact the replay reads is really committed.
"""

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "experiments"))

# The experiment modules import matplotlib at module level; it is a dev extra.
pytest.importorskip("matplotlib")

import reproduce_figures  # noqa: E402


def test_declared_figures_match_the_figures_directory():
    on_disk = {p.name for p in (ROOT / "figures").glob("*.png")}
    declared = set(reproduce_figures.FIGURES)

    unreproducible = sorted(on_disk - declared)
    stale = sorted(declared - on_disk)
    assert not unreproducible, (
        "figures/ contains files reproduce_figures.py does not regenerate "
        f"(add them to FIGURES and call their producer in main()): {unreproducible}"
    )
    assert not stale, f"FIGURES names files that are not in figures/: {stale}"


def test_figure_list_has_no_duplicates():
    assert len(set(reproduce_figures.FIGURES)) == len(reproduce_figures.FIGURES)


def test_every_artifact_the_figures_depend_on_is_committed():
    """The CSVs and checkpoints must be in the repo, so a fresh clone can
    reproduce every figure without training anything."""
    missing = reproduce_figures.check_artifacts()
    assert missing == [], f"missing committed artifacts: {missing}"


def test_committed_checkpoints_load_and_match_their_experiment():
    """Each committed checkpoint rebuilds into a usable field.

    Loading is strict about shapes, so this also pins that the stored config
    still matches what the experiment code builds today -- the failure mode
    where a refactor silently orphans the weights.
    """
    from common import ckpt_path
    from pinn.checkpoints import load_model

    import torch

    for name in reproduce_figures.CKPT_FILES:
        model, meta = load_model(ckpt_path(name))
        assert meta, f"{name} carries no provenance metadata"
        out = model(torch.zeros(4, 2))
        assert out.shape == (4, 1), f"{name} produced {tuple(out.shape)}"
